name: Deploy Web Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  deploy_web:
    name: Deploy Web Preview
    type: deploy
    environment: preview

  comment:
    name: Comment Preview URL
    needs:
      - deploy_web
    type: github-comment
    params:
      build_ids: []
      update_group_ids: []
      deployment_ids:
        - ${{ needs.deploy_web.outputs.deploy_identifier }}
